import * as DocumentPicker from 'expo-document-picker';
import { File } from 'expo-file-system';
import { useState } from 'react';
import { Pressable, StyleSheet, TextInput } from 'react-native';
import { useAuth } from '@/auth/AuthContext';
import { apiRequest } from '@/lib/api';
import { Card, Screen } from '@/components/screen';
import { ThemedText } from '@/components/themed-text';
export default function AdminLabScreen() {
  const { token } = useAuth(); const [name, setName] = useState<string>(); const [uri, setUri] = useState<string>(); const [mime, setMime] = useState('application/pdf'); const [prompt, setPrompt] = useState('Extraia os campos relevantes deste documento.'); const [result, setResult] = useState<Record<string, unknown>>(); const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false);
  async function pick() { const picked = await DocumentPicker.getDocumentAsync({ type: ['application/pdf', 'image/png', 'image/jpeg'], copyToCacheDirectory: true }); if (!picked.canceled) { const item = picked.assets[0]; setName(item.name); setUri(item.uri); setMime(item.mimeType ?? 'application/pdf'); } }
  async function run() { if (!uri) return; setBusy(true); setMessage(undefined); try { const profile = await apiRequest<Record<string, unknown>>('/users/profile', {}, token ?? undefined); if (!profile.data?.is_admin && !profile.data?.isAdmin) throw new Error('Acesso administrativo necessário.'); const base64 = await new File(uri).base64(); const type = mime.includes('jpeg') ? 'jpeg' : mime.includes('png') ? 'png' : 'pdf'; const r = await apiRequest<Record<string, unknown>>('/admin/lab/run', { method: 'POST', body: JSON.stringify({ base64Document: base64, documentType: type, fileName: name, mode: 'prompt', prompt }) }, token ?? undefined); setResult(r.data); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao executar laboratório.'); } finally { setBusy(false); } }
  return <Screen title="Admin Lab"><Card><ThemedText type="smallBold">Documento de teste</ThemedText><Pressable onPress={pick} style={styles.secondary}><ThemedText>{name ?? 'Selecionar documento'}</ThemedText></Pressable><ThemedText type="smallBold">Prompt</ThemedText><TextInput value={prompt} onChangeText={setPrompt} multiline style={styles.prompt} placeholder="Descreva o que extrair do documento" /><Pressable disabled={!uri || busy} onPress={run} style={styles.button}><ThemedText style={styles.white}>{busy ? 'Executando...' : 'Executar teste'}</ThemedText></Pressable></Card>{message && <ThemedText>{message}</ThemedText>}{result && <Card><ThemedText type="smallBold">Resultado</ThemedText><ThemedText>{JSON.stringify(result, null, 2)}</ThemedText></Card>}</Screen>;
}
const styles = StyleSheet.create({ secondary: { padding: 12, borderWidth: 1, borderColor: '#94a3b8', borderRadius: 9, alignItems: 'center', marginVertical: 10 }, prompt: { minHeight: 110, borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 9, padding: 11, textAlignVertical: 'top', backgroundColor: '#fff' }, button: { padding: 13, borderRadius: 9, backgroundColor: '#208AEF', alignItems: 'center' }, white: { color: '#fff', fontWeight: '700' } });
