import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, TextInput } from 'react-native';
import { useAuth } from '@/auth/AuthContext';
import { apiRequest } from '@/lib/api';
import { Card, LoadingOrError, Screen } from '@/components/screen';
import { ThemedText } from '@/components/themed-text';
type Item = Record<string, unknown>;
const idOf = (item: Item) => String(item.document_id ?? item.documentId ?? item.user_id ?? item.userId ?? item.group_id ?? item.groupId ?? '');
export default function AssignmentsScreen() {
  const { token } = useAuth(); const [companyId, setCompanyId] = useState(''); const [items, setItems] = useState<Item[]>([]); const [members, setMembers] = useState<Item[]>([]); const [groups, setGroups] = useState<Item[]>([]); const [selected, setSelected] = useState<string>(); const [userIds, setUserIds] = useState<string[]>([]); const [groupIds, setGroupIds] = useState<string[]>([]); const [sla, setSla] = useState(''); const [confidence, setConfidence] = useState(''); const [error, setError] = useState<string>(); const [message, setMessage] = useState<string>(); const [loading, setLoading] = useState(true);
  useEffect(() => { apiRequest<Item>('/users/profile', {}, token ?? undefined).then(async (p) => { const c = p.data?.company as Item | undefined; const id = String(c?.company_id ?? c?.companyId ?? ''); if (!id) throw new Error('Usuário sem empresa.'); setCompanyId(id); const [classes, memberResponse, groupResponse] = await Promise.all([apiRequest<Item[]>(`/users/company/${id}/document-classes`, {}, token ?? undefined), apiRequest<{ members?: Item[] }>(`/users/company/${id}/members`, {}, token ?? undefined), apiRequest<Item[]>(`/users/company/${id}/groups`, {}, token ?? undefined)]); setItems(classes.data ?? []); setMembers(memberResponse.data?.members ?? []); setGroups(groupResponse.data ?? []); }).catch(e => setError(e instanceof Error ? e.message : 'Falha ao carregar atribuições.')).finally(() => setLoading(false)); }, [token]);
  async function selectDocument(id: string) { setSelected(id); const item = items.find((entry) => idOf(entry) === id); setSla(String(item?.sla_days ?? item?.slaDays ?? '')); setConfidence(String(item?.min_validation_confidence ?? item?.minValidationConfidence ?? '')); try { const r = await apiRequest<{ userIds?: string[]; groupIds?: string[] }>(`/users/company/${companyId}/document-classes/${id}/members`, {}, token ?? undefined); setUserIds(r.data?.userIds ?? []); setGroupIds(r.data?.groupIds ?? []); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao carregar responsáveis.'); } }
  function toggle(values: string[], value: string, setter: (next: string[]) => void) { setter(values.indexOf(value) !== -1 ? values.filter((item) => item !== value) : [...values, value]); }
  async function save() { if (!selected) return; try { await Promise.all([apiRequest(`/users/company/${companyId}/document-classes/${selected}/members`, { method: 'PUT', body: JSON.stringify({ userIds, groupIds }) }, token ?? undefined), apiRequest(`/users/company/${companyId}/document-classes/${selected}/sla`, { method: 'PUT', body: JSON.stringify({ slaDays: sla === '' ? null : Number(sla) }) }, token ?? undefined), apiRequest(`/users/company/${companyId}/document-classes/${selected}/min-confidence`, { method: 'PUT', body: JSON.stringify({ minValidationConfidence: confidence === '' ? null : Number(confidence) }) }, token ?? undefined)]); setMessage('Atribuições e parâmetros atualizados.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao salvar atribuições.'); } }
  return <Screen title="Atribuições"><LoadingOrError loading={loading} error={error} />{!loading && items.length === 0 && !error && <ThemedText>Nenhuma classe encontrada.</ThemedText>}{items.map((item) => { const id = idOf(item); return <Pressable key={id} onPress={() => void selectDocument(id)}><Card><ThemedText type="smallBold">{String(item.name ?? item.document_name ?? item.documentName ?? 'Classe de documento')}</ThemedText><ThemedText>{String(item.members_count ?? item.membersCount ?? 0)} membros atribuídos</ThemedText>{selected === id && <><ThemedText type="smallBold">Parâmetros</ThemedText><TextInput value={sla} onChangeText={setSla} placeholder="SLA em dias (vazio = padrão)" keyboardType="numeric" style={styles.input} /><TextInput value={confidence} onChangeText={setConfidence} placeholder="Confiança mínima (0 a 1)" keyboardType="decimal-pad" style={styles.input} /><ThemedText type="smallBold">Usuários</ThemedText>{members.map((member) => { const memberId = idOf(member); return <Pressable key={memberId} onPress={() => toggle(userIds, memberId, setUserIds)}><ThemedText>{userIds.indexOf(memberId) !== -1 ? '☑' : '☐'} {String(member.first_name ?? member.firstName ?? member.email ?? 'Usuário')}</ThemedText></Pressable>; })}<ThemedText type="smallBold">Grupos</ThemedText>{groups.map((group) => { const groupId = idOf(group); return <Pressable key={groupId} onPress={() => toggle(groupIds, groupId, setGroupIds)}><ThemedText>{groupIds.indexOf(groupId) !== -1 ? '☑' : '☐'} {String(group.name ?? 'Grupo')}</ThemedText></Pressable>; })}<Pressable onPress={() => void save()} style={styles.button}><ThemedText style={styles.white}>Salvar atribuições</ThemedText></Pressable></>}</Card></Pressable>; })}{message && <ThemedText>{message}</ThemedText>}</Screen>;
}
const styles = StyleSheet.create({ input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 12, backgroundColor: '#fff', marginTop: 6 }, button: { padding: 12, borderRadius: 9, backgroundColor: '#208AEF', alignItems: 'center', marginTop: 8 }, white: { color: '#fff', fontWeight: '700' } });
