import { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet, TextInput } from 'react-native';
import { useAuth } from '@/auth/AuthContext';
import { apiRequest } from '@/lib/api';
import { Card, LoadingOrError, Screen } from '@/components/screen';
import { ThemedText } from '@/components/themed-text';
type Conversation = Record<string, unknown>; type Message = Record<string, unknown>;
export default function ChatScreen() {
  const { token } = useAuth(); const [conversations, setConversations] = useState<Conversation[]>([]); const [active, setActive] = useState<string>(); const [messages, setMessages] = useState<Message[]>([]); const [content, setContent] = useState(''); const [error, setError] = useState<string>(); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const load = useCallback(() => apiRequest<Conversation[]>('/engine/ai-chat/conversations', {}, token ?? undefined).then(r => { const list = r.data ?? []; setConversations(list); if (!active && list[0]) setActive(String(list[0].conversation_id ?? list[0].conversationId)); }).catch(e => setError(e.message)).finally(() => setLoading(false)), [token, active]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (active) apiRequest<Message[]>(`/engine/ai-chat/conversations/${active}/messages`, {}, token ?? undefined).then(r => setMessages(r.data ?? [])).catch(e => setError(e.message)); }, [active, token]);
  async function newConversation() { try { const r = await apiRequest<Conversation>('/engine/ai-chat/conversations', { method: 'POST', body: JSON.stringify({ title: 'Nova conversa' }) }, token ?? undefined); const item = r.data; if (item) { const id = String(item.conversation_id ?? item.conversationId); setActive(id); setConversations((old) => [item, ...old]); setMessages([]); } } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao criar conversa.'); } }
  async function send() { if (!active || !content.trim() || busy) return; const text = content.trim(); setContent(''); setBusy(true); try { const response = await fetch(`${process.env.EXPO_PUBLIC_BACKEND_URL ?? 'https://api.flaxia.com.br'}/engine/ai-chat/conversations/${active}/messages`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify({ content: text }) }); const raw = await response.text(); const final = raw.split('\n').map((line) => { try { return JSON.parse(line) as Record<string, unknown>; } catch { return null; } }).find((event) => event?.type === 'final'); setMessages((old) => [...old, { role: 'user', content: text }, { role: 'assistant', content: String(final?.content ?? 'Não foi possível obter uma resposta.') }]); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao enviar mensagem.'); } finally { setBusy(false); } }
  return <Screen title="Chat IA"><LoadingOrError loading={loading} error={error} />{!loading && <><Pressable onPress={newConversation} style={styles.button}><ThemedText style={styles.white}>Nova conversa</ThemedText></Pressable>{conversations.map((item, i) => { const id = String(item.conversation_id ?? item.conversationId ?? i); return <Pressable key={id} onPress={() => setActive(id)}><Card><ThemedText type="smallBold">{String(item.title ?? 'Conversa')}</ThemedText></Card></Pressable>; })}{active && <>{messages.map((item, i) => <Card key={String(item.message_id ?? i)}><ThemedText type="smallBold">{String(item.role ?? '')}</ThemedText><ThemedText>{String(item.content ?? '')}</ThemedText></Card>)}<TextInput value={content} onChangeText={setContent} placeholder="Pergunte algo..." multiline style={styles.input} /><Pressable onPress={send} disabled={busy} style={styles.button}><ThemedText style={styles.white}>{busy ? 'Enviando...' : 'Enviar'}</ThemedText></Pressable></>}</>}</Screen>;
}
const styles = StyleSheet.create({ input: { minHeight: 80, borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 13, backgroundColor: '#fff' }, button: { padding: 14, borderRadius: 10, backgroundColor: '#208AEF', alignItems: 'center' }, white: { color: '#fff', fontWeight: '700' } });
