import { useEffect, useState } from 'react';
import { Screen, Card, LoadingOrError } from '@/components/screen';
import { Alert, Pressable, StyleSheet, TextInput } from 'react-native';
import { router } from 'expo-router';
import { ThemedText } from '@/components/themed-text';
import { useAuth } from '@/auth/AuthContext';
import { apiRequest } from '@/lib/api';

type Profile = Record<string, unknown>;
export default function CompanyScreen() {
  const { token, signOut } = useAuth(); const [profile, setProfile] = useState<Profile>(); const [members, setMembers] = useState<Profile[]>([]); const [error, setError] = useState<string>(); const [email, setEmail] = useState(''); const [name, setName] = useState(''); const [editingName, setEditingName] = useState(false); const [message, setMessage] = useState<string>();
  useEffect(() => { apiRequest<Profile>('/users/profile', {}, token ?? undefined).then(async (r) => { setProfile(r.data); const company = r.data?.company as Profile | undefined; setName(String(company?.name ?? '')); const id = company?.company_id ?? company?.companyId; if (id) { const m = await apiRequest<Profile[] | { members?: Profile[] }>(`/users/company/${id}/members`, {}, token ?? undefined); setMembers(Array.isArray(m.data) ? m.data : (m.data?.members ?? [])); } }).catch(e => setError(e.message)); }, [token]);
  const company = profile?.company as Profile | undefined;
  async function invite() { const id = company?.company_id ?? company?.companyId; if (!id || !email.trim()) return; try { const r = await apiRequest('/users/company/invites', { method: 'POST', body: JSON.stringify({ companyId: id, email: email.trim() }) }, token ?? undefined); setMessage(r.message ?? 'Convite criado.'); setEmail(''); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao enviar convite.'); } }
  const currentUserId = String(profile?.user_id ?? profile?.userId ?? '');
  const currentMember = members.find((member) => String(member.user_id ?? member.userId) === currentUserId);
  const canManage = Boolean(currentMember?.is_owner ?? currentMember?.isOwner) || [1, 2, 4].indexOf(Number(currentMember?.role_id ?? currentMember?.roleId)) !== -1;
  const isOwner = Boolean(currentMember?.is_owner ?? currentMember?.isOwner);
  async function rename() { if (!name.trim()) return; try { await apiRequest('/users/company/name', { method: 'POST', body: JSON.stringify({ name: name.trim() }) }, token ?? undefined); setEditingName(false); setMessage('Nome da empresa atualizado.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao renomear empresa.'); } }
  function deleteCompany() { Alert.alert('Excluir empresa', 'Esta ação remove a empresa, membros e convites permanentemente.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Excluir', style: 'destructive', onPress: async () => { try { await apiRequest('/users/company', { method: 'DELETE', body: JSON.stringify({ companyId: company?.company_id ?? company?.companyId }) }, token ?? undefined); await signOut(); router.replace('/profile'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao excluir empresa.'); } } }]); }
  return <Screen title="Empresa"><LoadingOrError loading={!profile && !error} error={error} />{profile && <><Card><ThemedText type="small">Empresa</ThemedText>{editingName ? <><TextInput value={name} onChangeText={setName} style={styles.input} /><Pressable onPress={() => void rename()} style={styles.button}><ThemedText style={styles.white}>Salvar nome</ThemedText></Pressable><Pressable onPress={() => { setEditingName(false); setName(String(company?.name ?? '')); }}><ThemedText type="linkPrimary">Cancelar</ThemedText></Pressable></> : <><ThemedText type="subtitle">{String(company?.name ?? 'Sem empresa')}</ThemedText>{canManage && <Pressable onPress={() => setEditingName(true)}><ThemedText type="linkPrimary">Renomear empresa</ThemedText></Pressable>}</>}</Card>{canManage && <><ThemedText type="subtitle">Convidar membro</ThemedText><TextInput value={email} onChangeText={setEmail} placeholder="E-mail do membro" keyboardType="email-address" autoCapitalize="none" style={styles.input} /><Pressable onPress={invite} style={styles.button}><ThemedText style={styles.white}>Enviar convite</ThemedText></Pressable></>}{message && <ThemedText>{message}</ThemedText>}<ThemedText type="subtitle">Membros</ThemedText>{members.map((member, i) => { const id = String(member.user_id ?? member.userId ?? i); return <Pressable key={id} onPress={() => router.push(`/company/members/${id}`)}><Card><ThemedText type="smallBold">{String(member.first_name ?? member.firstName ?? '')} {String(member.last_name ?? member.lastName ?? '')}</ThemedText><ThemedText>{String(member.email ?? '')}</ThemedText>{canManage && id !== currentUserId && !Boolean(member.is_owner ?? member.isOwner) && <ThemedText type="linkPrimary">Gerenciar membro</ThemedText>}</Card></Pressable>; })}{isOwner && <Card><ThemedText type="smallBold">Zona de perigo</ThemedText><ThemedText>Excluir a empresa remove permanentemente seus membros e convites.</ThemedText><Pressable onPress={deleteCompany}><ThemedText style={styles.danger}>Excluir empresa</ThemedText></Pressable></Card>}</>}</Screen>;
}
const styles = StyleSheet.create({ input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 13, backgroundColor: '#fff' }, button: { padding: 14, borderRadius: 10, backgroundColor: '#208AEF', alignItems: 'center' }, white: { color: '#fff', fontWeight: '700' }, danger: { color: '#b91c1c', fontWeight: '700' } });
