import { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet, Switch, View } from 'react-native';
import { File } from 'expo-file-system';
import { Card, Field, FilterChip, LoadingOrError, Screen } from '@/components/screen';
import { ThemedText } from '@/components/themed-text';
import { useTheme } from '@/hooks/use-theme';
import { useAuth } from '@/auth/AuthContext';
import { apiRequest } from '@/lib/api';
import { pickDocument, PickedDocument } from '@/lib/document-picker';

type Field = Record<string, unknown>;
type DocumentModel = Record<string, unknown> & { fields?: Field[] };
type Mode = 'fields' | 'prompt';
const idOf = (item: DocumentModel) => String(item.document_id ?? item.documentId ?? '');
const displayNameOf = (item: DocumentModel) => String(item.display_name ?? item.displayName ?? item.name ?? 'Documento');
const fieldNameOf = (field: Field) => String(field.display_name ?? field.displayName ?? field.name ?? field.fieldName ?? '');

export default function DocumentsScreen() {
  const { token } = useAuth();
  const theme = useTheme();
  const [items, setItems] = useState<DocumentModel[]>([]); const [selected, setSelected] = useState<DocumentModel>(); const [editing, setEditing] = useState(false);
  const [name, setName] = useState(''); const [description, setDescription] = useState(''); const [mode, setMode] = useState<Mode>('fields'); const [prompt, setPrompt] = useState('');
  const [fields, setFields] = useState<Field[]>([{ displayName: '', fieldPrompt: '', fieldType: 'text' }]); const [validating, setValidating] = useState(true); const [webhook, setWebhook] = useState(false);
  const [error, setError] = useState<string>(); const [message, setMessage] = useState<string>(); const [saving, setSaving] = useState(false);
  const [analyzing, setAnalyzing] = useState(false);
  const load = useCallback(async () => { try { setError(undefined); const response = await apiRequest<DocumentModel[]>('/engine/documents', {}, token ?? undefined); setItems(Array.isArray(response.data) ? response.data : []); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao carregar documentos.'); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  function openEditor(item?: DocumentModel) { setSelected(item); setName(item ? displayNameOf(item) : ''); setDescription(String(item?.description ?? '')); const raw = String(item?.document_process_method ?? item?.documentProcessMethod ?? '').toLowerCase(); setMode(raw === 'prompt' || raw === '2' ? 'prompt' : 'fields'); setPrompt(String(item?.prompt ?? '')); setFields(item?.fields?.length ? item.fields : [{ displayName: '', fieldPrompt: '', fieldType: 'text' }]); setValidating(item?.is_validating !== false && item?.isValidating !== false); setWebhook((item?.export_targets as unknown[] | undefined)?.includes('webhook') ?? false); setMessage(undefined); setEditing(true); }
  function updateField(index: number, key: string, value: string) { setFields(current => current.map((field, i) => i === index ? { ...field, [key]: value } : field)); }
  async function save() { if (!name.trim()) { setMessage('Informe o nome do documento.'); return; } if (mode === 'prompt' && !prompt.trim()) { setMessage('Informe o prompt do documento.'); return; } const documentType = name.trim().toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, ''); const normalizedFields = fields.filter(fieldNameOf).map((field, index) => ({ ...field, fieldName: fieldNameOf(field).toLowerCase().replace(/[^a-z0-9]+/g, '_'), fieldIndex: index })); const payload = { documentType, displayName: name.trim(), description: description.trim(), fields: mode === 'fields' ? normalizedFields : null, prompt: mode === 'prompt' ? prompt.trim() : null, documentProcessMethod: mode === 'prompt' ? 2 : 1, isValidating: validating, minValidationConfidence: null, exportEnabled: true, exportTargets: webhook ? ['webhook'] : [], includeInWebhookExport: webhook }; setSaving(true); setMessage(undefined); try { if (selected) await apiRequest('/engine/update_document', { method: 'PUT', body: JSON.stringify({ ...payload, documentId: idOf(selected) }) }, token ?? undefined); else await apiRequest('/engine/create_manual_document', { method: 'POST', body: JSON.stringify(payload) }, token ?? undefined); setMessage(selected ? 'Documento atualizado.' : 'Documento criado.'); setEditing(false); setSelected(undefined); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao salvar documento.'); } finally { setSaving(false); } }
  async function remove(item: DocumentModel) { const id = idOf(item); if (!id) return; try { await apiRequest(`/engine/document/${id}`, { method: 'DELETE' }, token ?? undefined); setMessage('Documento excluído.'); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao excluir documento.'); } }
  async function createFromDocument() {
    const picked: PickedDocument | undefined = await pickDocument(); if (!picked) return;
    setAnalyzing(true); setMessage(undefined);
    try {
      const type = picked.mimeType.includes('png') ? 'png' : picked.mimeType.includes('webp') ? 'webp' : picked.mimeType.includes('gif') ? 'gif' : picked.mimeType.includes('jpeg') || picked.mimeType.includes('jpg') ? 'jpeg' : 'pdf';
      const response = await apiRequest<DocumentModel>('/engine/create_document_class', { method: 'POST', body: JSON.stringify({ documentType: type, base64Document: await new File(picked.uri).base64() }) }, token ?? undefined);
      const created = response.data;
      if (!created) throw new Error(response.message ?? 'Não foi possível analisar o documento.');
      openEditor(created); setMessage(`Modelo criado a partir de ${picked.name}. Revise e salve.`);
    } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao criar a partir do documento.'); }
    finally { setAnalyzing(false); }
  }
  if (editing) return <Screen title={selected ? 'Editar documento' : 'Novo documento'}><View style={styles.form}><Field value={name} onChangeText={setName} placeholder="Nome de exibição" /><Field value={description} onChangeText={setDescription} placeholder="Descrição" multiline /><View style={styles.segment}><FilterChip label="Campos" active={mode === 'fields'} onPress={() => setMode('fields')} style={styles.segmentButton} /><FilterChip label="Prompt" active={mode === 'prompt'} onPress={() => setMode('prompt')} style={styles.segmentButton} /></View>{mode === 'prompt' ? <Field value={prompt} onChangeText={setPrompt} placeholder="Descreva o que deve ser extraído..." style={styles.multiline} multiline /> : <><ThemedText type="smallBold">Campos extraídos</ThemedText>{fields.map((field, index) => <Card key={index}><Field value={fieldNameOf(field)} onChangeText={value => updateField(index, 'displayName', value)} placeholder="Nome do campo" /><Field value={String(field.fieldPrompt ?? '')} onChangeText={value => updateField(index, 'fieldPrompt', value)} placeholder="Instrução opcional" /><Pressable onPress={() => setFields(current => current.filter((_, i) => i !== index))}><ThemedText style={{ color: theme.danger, fontWeight: '700' }}>Remover campo</ThemedText></Pressable></Card>)}<Pressable onPress={() => setFields(current => [...current, { displayName: '', fieldPrompt: '', fieldType: 'text' }])}><ThemedText type="linkPrimary">+ Adicionar campo</ThemedText></Pressable></>}<View style={styles.option}><ThemedText>Exigir validação</ThemedText><Switch value={validating} onValueChange={setValidating} /></View><View style={styles.option}><ThemedText>Exportar para webhook</ThemedText><Switch value={webhook} onValueChange={setWebhook} /></View>{message && <ThemedText style={{ color: theme.danger }}>{message}</ThemedText>}<Pressable disabled={saving} onPress={() => void save()} style={styles.primary}><ThemedText style={styles.white}>{saving ? 'Salvando...' : 'Salvar documento'}</ThemedText></Pressable><Pressable onPress={() => { setEditing(false); setSelected(undefined); }}><ThemedText type="linkPrimary">Cancelar</ThemedText></Pressable></View></Screen>;
  return <Screen title="Documentos"><Pressable onPress={() => openEditor()} style={styles.primary}><ThemedText style={styles.white}>Novo documento</ThemedText></Pressable><Pressable disabled={analyzing} onPress={() => void createFromDocument()} style={[styles.secondary, { borderColor: theme.border, backgroundColor: theme.secondary }]}><ThemedText style={styles.secondaryLabel}>{analyzing ? 'Analisando documento...' : 'Criar a partir de arquivo, Fotos ou câmera'}</ThemedText></Pressable>{message && <ThemedText>{message}</ThemedText>}<LoadingOrError loading={!items.length && !error} error={error} />{!items.length && !error && <ThemedText>Nenhum documento cadastrado.</ThemedText>}{items.map((item, index) => <Card key={idOf(item) || index}><ThemedText type="smallBold">{displayNameOf(item)}</ThemedText><ThemedText>{String(item.description ?? 'Sem descrição')}</ThemedText><ThemedText>{String(item.prompt ? 'Prompt configurado' : `${item.fields?.length ?? 0} campo(s)`)}</ThemedText><View style={styles.actions}><Pressable onPress={() => openEditor(item)}><ThemedText type="linkPrimary">Editar</ThemedText></Pressable><Pressable onPress={() => void remove(item)}><ThemedText style={{ color: theme.danger, fontWeight: '700' }}>Excluir</ThemedText></Pressable></View></Card>)}</Screen>;
}
const styles = StyleSheet.create({ form: { gap: 12, paddingBottom: 30 }, multiline: { minHeight: 110, textAlignVertical: 'top' }, segment: { flexDirection: 'row', gap: 8 }, segmentButton: { flex: 1 }, option: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, actions: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 }, primary: { padding: 14, borderRadius: 10, backgroundColor: '#208AEF', alignItems: 'center' }, secondary: { padding: 13, borderRadius: 10, borderWidth: 1, alignItems: 'center' }, secondaryLabel: { fontWeight: '600', textAlign: 'center' }, white: { color: '#fff', fontWeight: '700' } });
