import * as WebBrowser from 'expo-web-browser';
import { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet } from 'react-native';
import { useAuth } from '@/auth/AuthContext';
import { apiRequest } from '@/lib/api';
import { Card, LoadingOrError, Screen } from '@/components/screen';
import { ThemedText } from '@/components/themed-text';
type Item = Record<string, unknown>;
type FilesResponse = { files?: Item[]; nextPageToken?: string };
export default function DriveScreen() {
  const { token } = useAuth(); const [connections, setConnections] = useState<Item[]>([]); const [selected, setSelected] = useState<string>(); const [files, setFiles] = useState<Item[]>([]); const [error, setError] = useState<string>(); const [message, setMessage] = useState<string>(); const [loadingFiles, setLoadingFiles] = useState(false);
  const load = useCallback(async () => { try { const response = await apiRequest<Item[]>('/integrations/google-drive?scope=user', {}, token ?? undefined); setConnections(response.data ?? []); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao carregar conexões Drive.'); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  async function connect() { try { const response = await apiRequest<{ authorizationUrl: string }>('/oauth/google/start?intent=drive_user', {}, token ?? undefined); if (response.data?.authorizationUrl) await WebBrowser.openBrowserAsync(response.data.authorizationUrl); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao iniciar conexão Drive.'); } }
  async function disconnect(id: string) { try { await apiRequest(`/integrations/google-drive/${id}`, { method: 'DELETE' }, token ?? undefined); setMessage('Conexão desconectada.'); if (selected === id) { setSelected(undefined); setFiles([]); } await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao desconectar Drive.'); } }
  async function browse(id: string) { setSelected(id); setLoadingFiles(true); try { const response = await apiRequest<FilesResponse>(`/integrations/google-drive/files?connectionId=${encodeURIComponent(id)}`, {}, token ?? undefined); setFiles(response.data?.files ?? []); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao carregar arquivos Drive.'); } finally { setLoadingFiles(false); } }
  async function importFile(file: Item) { if (!selected) return; try { await apiRequest('/integrations/google-drive/import', { method: 'POST', body: JSON.stringify({ connectionId: selected, fileIds: [String(file.id ?? file.fileId)], useClassifier: true }) }, token ?? undefined); setMessage('Arquivo enviado para processamento.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao importar arquivo.'); } }
  return <Screen title="Google Drive"><ThemedText>Conecte contas e importe arquivos para processamento.</ThemedText><Pressable onPress={() => void connect()} style={styles.button}><ThemedText style={styles.white}>Conectar Google Drive</ThemedText></Pressable>{message && <ThemedText>{message}</ThemedText>}<LoadingOrError loading={!connections.length && !error} error={error} />{connections.map((item, index) => { const id = String(item.id ?? item.connectionId ?? index); return <Card key={id}><ThemedText type="smallBold">{String(item.google_account_email ?? item.googleAccountEmail ?? item.email ?? 'Conta Google')}</ThemedText><ThemedText>Status: {String(item.status ?? 'conectado')}</ThemedText><Pressable onPress={() => void browse(id)}><ThemedText type="linkPrimary">Navegar arquivos</ThemedText></Pressable><Pressable onPress={() => void disconnect(id)}><ThemedText style={styles.danger}>Desconectar</ThemedText></Pressable></Card>; })}{selected && <Card><ThemedText type="subtitle">Arquivos Drive</ThemedText><LoadingOrError loading={loadingFiles} />{!loadingFiles && files.length === 0 && <ThemedText>Nenhum arquivo encontrado.</ThemedText>}{files.map((file, index) => <Card key={String(file.id ?? file.fileId ?? index)}><ThemedText type="smallBold">{String(file.name ?? file.fileName ?? 'Arquivo')}</ThemedText><ThemedText>{String(file.mimeType ?? file.mime_type ?? '')}</ThemedText><Pressable onPress={() => void importFile(file)}><ThemedText type="linkPrimary">Importar para processamento</ThemedText></Pressable></Card>)}</Card>}</Screen>;
}
const styles = StyleSheet.create({ button: { padding: 13, borderRadius: 9, backgroundColor: '#208AEF', alignItems: 'center' }, white: { color: '#fff', fontWeight: '700' }, danger: { color: '#b91c1c', fontWeight: '700' } });
