import { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet, TextInput } from 'react-native';
import { useAuth } from '@/auth/AuthContext';
import { apiRequest } from '@/lib/api';
import { Card, LoadingOrError, Screen } from '@/components/screen';
import { ThemedText } from '@/components/themed-text';
type Item = Record<string, unknown>;
export default function DriveWatchFoldersScreen() {
  const { token } = useAuth(); const [items, setItems] = useState<Item[]>([]); const [selected, setSelected] = useState<string>(); const [logs, setLogs] = useState<Item[]>([]); const [connectionId, setConnectionId] = useState(''); const [folderId, setFolderId] = useState(''); const [folderName, setFolderName] = useState(''); const [message, setMessage] = useState<string>(); const [error, setError] = useState<string>();
  const load = useCallback(async () => { try { const r = await apiRequest<Item[]>('/integrations/google-drive/watch-folders?scope=user', {}, token ?? undefined); setItems(r.data ?? []); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao carregar pastas monitoradas.'); } }, [token]);
  useEffect(() => { void load(); }, [load]);
  async function create() { if (!connectionId.trim() || !folderId.trim()) return; try { await apiRequest('/integrations/google-drive/watch-folders', { method: 'POST', body: JSON.stringify({ connectionId: connectionId.trim(), folderId: folderId.trim(), folderName: folderName.trim() || undefined, enabled: true, pollIntervalSecs: 300 }) }, token ?? undefined); setMessage('Pasta monitorada criada.'); setConnectionId(''); setFolderId(''); setFolderName(''); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao criar monitoramento.'); } }
  async function remove(id: string) { try { await apiRequest(`/integrations/google-drive/watch-folders/${id}`, { method: 'DELETE' }, token ?? undefined); setMessage('Monitoramento removido.'); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao remover monitoramento.'); } }
  async function showLog(id: string) { setSelected(id); try { const r = await apiRequest<Item[]>(`/integrations/google-drive/watch-folders/${id}/ingest-log?limit=50`, {}, token ?? undefined); setLogs(r.data ?? []); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao carregar histórico.'); } }
  return <Screen title="Pastas monitoradas"><ThemedText>Configure pastas do Google Drive para ingestão automática.</ThemedText><Card><TextInput value={connectionId} onChangeText={setConnectionId} placeholder="ID da conexão Drive" style={styles.input} /><TextInput value={folderId} onChangeText={setFolderId} placeholder="ID da pasta Drive" style={styles.input} /><TextInput value={folderName} onChangeText={setFolderName} placeholder="Nome da pasta (opcional)" style={styles.input} /><Pressable onPress={() => void create()} style={styles.button}><ThemedText style={styles.white}>Monitorar pasta</ThemedText></Pressable></Card>{message && <ThemedText>{message}</ThemedText>}<LoadingOrError loading={!items.length && !error} error={error} />{!items.length && !error && <ThemedText>Nenhuma pasta monitorada.</ThemedText>}{items.map((item, index) => { const id = String(item.id ?? item.watchFolderId ?? index); return <Card key={id}><ThemedText type="smallBold">{String(item.folder_name ?? item.folderName ?? item.folder_id ?? item.folderId ?? 'Pasta')}</ThemedText><ThemedText>Status: {Boolean(item.enabled) ? 'Ativa' : 'Inativa'}</ThemedText><Pressable onPress={() => void showLog(id)}><ThemedText type="linkPrimary">Ver histórico</ThemedText></Pressable><Pressable onPress={() => void remove(id)}><ThemedText style={styles.danger}>Remover monitoramento</ThemedText></Pressable>{selected === id && <Card><ThemedText type="smallBold">Histórico de ingestão</ThemedText>{logs.length === 0 && <ThemedText>Nenhum evento registrado.</ThemedText>}{logs.map((log, logIndex) => <ThemedText key={logIndex}>{String(log.file_name ?? log.fileName ?? 'Arquivo')} · {String(log.status ?? log.created_at ?? log.createdAt ?? '')}</ThemedText>)}</Card>}</Card>; })}</Screen>;
}
const styles = StyleSheet.create({ input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 9, padding: 11, backgroundColor: '#fff', marginBottom: 8 }, button: { padding: 13, borderRadius: 9, backgroundColor: '#208AEF', alignItems: 'center' }, white: { color: '#fff', fontWeight: '700' }, danger: { color: '#b91c1c', fontWeight: '700' } });
