import { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet, TextInput } from 'react-native';
import { useAuth } from '@/auth/AuthContext';
import { apiRequest } from '@/lib/api';
import { Card, LoadingOrError, Screen } from '@/components/screen';
import { ThemedText } from '@/components/themed-text';
type Item = Record<string, unknown>;
type Access = { hasDevelopmentAccess: boolean; hasOperationalAccess: boolean; hasAdminAccess: boolean; hasAiChatAccess: boolean };
const accessKeys: (keyof Access)[] = ['hasDevelopmentAccess', 'hasOperationalAccess', 'hasAdminAccess', 'hasAiChatAccess'];
const accessLabels: Record<keyof Access, string> = { hasDevelopmentAccess: 'Desenvolvimento', hasOperationalAccess: 'Operacional', hasAdminAccess: 'Admin', hasAiChatAccess: 'Chat IA' };
export default function GroupsScreen() {
  const { token } = useAuth(); const [companyId, setCompanyId] = useState<string>(); const [groups, setGroups] = useState<Item[]>([]); const [name, setName] = useState(''); const [error, setError] = useState<string>(); const [message, setMessage] = useState<string>(); const [editing, setEditing] = useState<string>(); const [draft, setDraft] = useState<Access>({ hasDevelopmentAccess: true, hasOperationalAccess: true, hasAdminAccess: false, hasAiChatAccess: false });
  const load = useCallback(async (id: string) => { try { const r = await apiRequest<Item[]>(`/users/company/${id}/groups`, {}, token ?? undefined); setGroups(r.data ?? []); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao carregar grupos.'); } }, [token]);
  useEffect(() => { apiRequest<Item>('/users/profile', {}, token ?? undefined).then(p => { const c = p.data?.company as Item | undefined; const id = String(c?.company_id ?? c?.companyId ?? ''); if (id) { setCompanyId(id); void load(id); } }).catch(e => setError(e.message)); }, [token, load]);
  async function create() { if (!companyId || !name.trim()) return; try { await apiRequest(`/users/company/${companyId}/groups`, { method: 'POST', body: JSON.stringify({ name: name.trim(), ...draft, userIds: [] }) }, token ?? undefined); setName(''); setMessage('Grupo criado.'); await load(companyId); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao criar grupo.'); } }
  async function save(id: string) { if (!companyId) return; try { await apiRequest(`/users/company/${companyId}/groups/${id}`, { method: 'PUT', body: JSON.stringify(draft) }, token ?? undefined); setEditing(undefined); setMessage('Permissões atualizadas.'); await load(companyId); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao atualizar grupo.'); } }
  async function remove(id: string) { if (!companyId) return; try { await apiRequest(`/users/company/${companyId}/groups/${id}`, { method: 'DELETE' }, token ?? undefined); await load(companyId); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao remover grupo.'); } }
  function startEdit(group: Item) { setEditing(String(group.group_id ?? group.groupId)); setDraft(Object.fromEntries(accessKeys.map((key) => [key, Boolean(group[key])])) as Access); }
  return <Screen title="Grupos"><TextInput value={name} onChangeText={setName} placeholder="Nome do grupo" style={styles.input} /><ThemedText type="smallBold">Acessos do novo grupo</ThemedText>{accessKeys.map((key) => <Pressable key={key} onPress={() => setDraft((current) => ({ ...current, [key]: !current[key] }))}><ThemedText>{draft[key] ? '☑' : '☐'} {accessLabels[key]}</ThemedText></Pressable>)}<Pressable onPress={create} style={styles.button}><ThemedText style={styles.white}>Criar grupo</ThemedText></Pressable>{message && <ThemedText>{message}</ThemedText>}<LoadingOrError loading={!groups.length && !error} error={error} />{groups.map((group, i) => { const id = String(group.group_id ?? group.groupId ?? i); return <Card key={id}><ThemedText type="smallBold">{String(group.name ?? 'Grupo')}</ThemedText>{editing === id ? <>{accessKeys.map((key) => <Pressable key={key} onPress={() => setDraft((current) => ({ ...current, [key]: !current[key] }))}><ThemedText>{draft[key] ? '☑' : '☐'} {accessLabels[key]}</ThemedText></Pressable>)}<Pressable onPress={() => void save(id)}><ThemedText type="linkPrimary">Salvar acessos</ThemedText></Pressable></> : <><ThemedText>{accessKeys.filter((key) => Boolean(group[key])).map((key) => accessLabels[key]).join(', ') || 'Sem acessos'}</ThemedText><Pressable onPress={() => startEdit(group)}><ThemedText type="linkPrimary">Editar acessos</ThemedText></Pressable></>}<Pressable onPress={() => void remove(id)}><ThemedText style={styles.danger}>Remover grupo</ThemedText></Pressable></Card>; })}</Screen>;
}
const styles = StyleSheet.create({ input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 13, backgroundColor: '#fff' }, button: { padding: 14, borderRadius: 10, backgroundColor: '#208AEF', alignItems: 'center' }, white: { color: '#fff', fontWeight: '700' }, danger: { color: '#b91c1c', fontWeight: '700' } });
