import * as WebBrowser from 'expo-web-browser';
import { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet, TextInput } from 'react-native';
import { useAuth } from '@/auth/AuthContext';
import { apiRequest } from '@/lib/api';
import { Card, LoadingOrError, Screen } from '@/components/screen';
import { ThemedText } from '@/components/themed-text';
type Item = Record<string, unknown>;
export default function IntegrationsScreen() {
  const { token } = useAuth(); const [google, setGoogle] = useState<Item>(); const [s3, setS3] = useState<Item[]>([]); const [bucket, setBucket] = useState(''); const [region, setRegion] = useState(''); const [accessKey, setAccessKey] = useState(''); const [secret, setSecret] = useState(''); const [message, setMessage] = useState<string>(); const [error, setError] = useState<string>();
  const load = useCallback(() => Promise.all([apiRequest<Item>('/integrations/google/identity', {}, token ?? undefined), apiRequest<Item[]>('/integrations/s3/connections?scope=user', {}, token ?? undefined)]).then(([g, s]) => { setGoogle(g.data); setS3(s.data ?? []); }).catch(e => setError(e.message)), [token]);
  useEffect(() => { void load(); }, [load]);
  async function connectGoogle() { try { const r = await apiRequest<{ authorizationUrl: string }>('/oauth/google/start?intent=link', {}, token ?? undefined); if (r.data?.authorizationUrl) await WebBrowser.openBrowserAsync(r.data.authorizationUrl); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao iniciar Google.'); } }
  async function unlinkGoogle() { try { await apiRequest('/integrations/google/identity', { method: 'DELETE' }, token ?? undefined); setMessage('Conta Google desconectada.'); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao desconectar Google.'); } }
  async function createS3() { if (!bucket || !accessKey || !secret) return; try { await apiRequest('/integrations/s3/connections', { method: 'POST', body: JSON.stringify({ scope: 'user', displayName: bucket, provider: 's3', bucket, region, accessKeyId: accessKey, secretAccessKey: secret }) }, token ?? undefined); setMessage('Conexão S3 criada.'); setBucket(''); setRegion(''); setAccessKey(''); setSecret(''); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao criar conexão S3.'); } }
  async function removeS3(id: string) { try { await apiRequest(`/integrations/s3/connections/${id}`, { method: 'DELETE' }, token ?? undefined); setMessage('Conexão S3 removida.'); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao remover S3.'); } }
  const linked = Boolean(google?.linked);
  return <Screen title="Integrações"><LoadingOrError loading={!google && !error} error={error} /><Card><ThemedText type="smallBold">Google Drive</ThemedText><ThemedText>{linked ? `Conectado: ${String(google?.email ?? '')}` : 'Não conectado'}</ThemedText><Pressable onPress={connectGoogle} style={styles.button}><ThemedText style={styles.white}>{linked ? 'Reconectar' : 'Conectar Google'}</ThemedText></Pressable>{linked && <Pressable onPress={() => void unlinkGoogle()}><ThemedText style={styles.danger}>Desconectar conta</ThemedText></Pressable>}</Card><Card><ThemedText type="smallBold">Nova conexão S3</ThemedText><TextInput value={bucket} onChangeText={setBucket} placeholder="Bucket" style={styles.input} /><TextInput value={region} onChangeText={setRegion} placeholder="Região" style={styles.input} /><TextInput value={accessKey} onChangeText={setAccessKey} placeholder="Access key" style={styles.input} /><TextInput secureTextEntry value={secret} onChangeText={setSecret} placeholder="Secret key" style={styles.input} /><Pressable onPress={createS3} style={styles.button}><ThemedText style={styles.white}>Salvar conexão</ThemedText></Pressable></Card>{message && <ThemedText>{message}</ThemedText>}<ThemedText type="subtitle">Conexões S3</ThemedText>{s3.map((item, i) => { const id = String(item.id ?? i); return <Card key={id}><ThemedText type="smallBold">{String(item.display_name ?? item.displayName ?? item.bucket ?? '')}</ThemedText><ThemedText>Status: {String(item.status ?? '')}</ThemedText><Pressable onPress={() => void removeS3(id)}><ThemedText style={styles.danger}>Remover conexão</ThemedText></Pressable></Card>; })}</Screen>;
}
const styles = StyleSheet.create({ input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 9, padding: 11, backgroundColor: '#fff' }, button: { padding: 13, borderRadius: 9, backgroundColor: '#208AEF', alignItems: 'center' }, white: { color: '#fff', fontWeight: '700' }, danger: { color: '#b91c1c', fontWeight: '700' } });
