import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { useAuth } from '@/auth/AuthContext';
import { apiRequest } from '@/lib/api';
import { Card, LoadingOrError, Screen } from '@/components/screen';
import { ThemedText } from '@/components/themed-text';
type Job = Record<string, unknown>;
const statuses = ['all', 'completed', 'processing', 'waiting_validation', 'failed', 'rejected'] as const;
export default function JobsScreen() {
  const { token } = useAuth(); const [jobs, setJobs] = useState<Job[]>([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState<(typeof statuses)[number]>('all'); const [page, setPage] = useState(0); const [total, setTotal] = useState(0); const [loading, setLoading] = useState(true); const [error, setError] = useState<string>();
  useEffect(() => { const timer = setTimeout(() => { const load = async () => { try { setLoading(true); const queryParams = new URLSearchParams({ page: String(page), pageSize: '20' }); if (status !== 'all') queryParams.set('status', status); const response = await apiRequest<{ items?: Job[]; total?: number }>(`/engine/processing_jobs?${queryParams.toString()}`, {}, token ?? undefined); const items = response.data?.items ?? []; const normalized = query.trim().toLowerCase(); setJobs(normalized ? items.filter((job) => String(job.file_name ?? job.fileName ?? '').toLowerCase().includes(normalized)) : items); setTotal(Number(response.data?.total ?? items.length)); setError(undefined); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao carregar jobs.'); } finally { setLoading(false); } }; void load(); }, 200); return () => clearTimeout(timer); }, [token, page, status, query]);
  useEffect(() => { setPage(0); }, [status]);
  const totalPages = Math.max(1, Math.ceil(total / 20));
  return <Screen title="Jobs de processamento"><TextInput value={query} onChangeText={setQuery} placeholder="Buscar por arquivo" style={styles.input} autoCapitalize="none" /><View style={styles.filters}>{statuses.map((item) => <Pressable key={item} onPress={() => setStatus(item)} style={[styles.filter, status === item && styles.active]}><ThemedText>{item === 'all' ? 'Todos' : item.replace('_', ' ')}</ThemedText></Pressable>)}</View><LoadingOrError loading={loading} error={error} />{!loading && jobs.length === 0 && !error && <ThemedText>Nenhum job encontrado.</ThemedText>}{jobs.map((job, i) => { const id = String(job.process_job_id ?? job.processJobId ?? job.processing_job_id ?? job.processingJobId ?? i); return <Pressable key={id} onPress={() => router.push(`/jobs/${id}`)}><Card><ThemedText type="smallBold">{String(job.file_name ?? job.fileName ?? 'Processamento')}</ThemedText><ThemedText>Status: {String(job.status ?? 'desconhecido')}</ThemedText><ThemedText>{String(job.started_at ?? job.startedAt ?? '')}</ThemedText></Card></Pressable>; })}<View style={styles.pagination}><Pressable disabled={page === 0} onPress={() => setPage((current) => Math.max(0, current - 1))}><ThemedText type="linkPrimary">Anterior</ThemedText></Pressable><ThemedText>Página {page + 1} de {totalPages}</ThemedText><Pressable disabled={page + 1 >= totalPages} onPress={() => setPage((current) => current + 1)}><ThemedText type="linkPrimary">Próxima</ThemedText></Pressable></View></Screen>;
}
const styles = StyleSheet.create({ input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 13, backgroundColor: '#fff' }, filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 }, filter: { padding: 8, borderRadius: 8, backgroundColor: '#e5e7eb' }, active: { backgroundColor: '#bfdbfe' }, pagination: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' } });
