import { useEffect, useState } from 'react';
import { Pressable, StyleSheet, TextInput } from 'react-native';
import { Screen, Card, LoadingOrError } from '@/components/screen';
import { ThemedText } from '@/components/themed-text';
import { apiRequest } from '@/lib/api';
import { useAuth } from '@/auth/AuthContext';
export default function ProfileScreen() {
  const { token, signOut } = useAuth(); const [profile, setProfile] = useState<Record<string, unknown>>(); const [error, setError] = useState<string>(); const [companyName, setCompanyName] = useState(''); const [message, setMessage] = useState<string>();
  useEffect(() => { apiRequest<Record<string, unknown>>('/users/profile', {}, token ?? undefined).then(r => { setProfile(r.data); setCompanyName(String((r.data?.company as Record<string, unknown> | undefined)?.name ?? '')); }).catch(e => setError(e.message)); }, [token]);
  async function createCompany() { if (!companyName.trim()) return; try { await apiRequest('/users/company', { method: 'POST', body: JSON.stringify({ name: companyName.trim() }) }, token ?? undefined); const r = await apiRequest<Record<string, unknown>>('/users/profile', {}, token ?? undefined); setProfile(r.data); setMessage('Empresa criada.'); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao criar empresa.'); } }
  const company = profile?.company as Record<string, unknown> | undefined;
  return <Screen title="Perfil"><LoadingOrError loading={!profile && !error} error={error} />{profile && <><Card><ThemedText type="smallBold">{String(profile.first_name ?? profile.firstName ?? '')} {String(profile.last_name ?? profile.lastName ?? '')}</ThemedText><ThemedText>{String(profile.email ?? '')}</ThemedText><ThemedText>{profile.email_verified || profile.emailVerified ? 'E-mail verificado' : 'E-mail não verificado'}</ThemedText></Card>{company ? <Card><ThemedText type="smallBold">Empresa</ThemedText><ThemedText>{String(company.name ?? '')}</ThemedText><ThemedText>{String(company.owner_user_id ?? company.ownerUserId) === String(profile.user_id ?? profile.userId) ? 'Proprietário' : 'Membro'}</ThemedText></Card> : <Card><ThemedText type="smallBold">Você ainda não possui uma empresa</ThemedText><TextInput value={companyName} onChangeText={setCompanyName} placeholder="Nome da empresa" style={styles.input} /><Pressable onPress={() => void createCompany()} style={styles.create}><ThemedText style={styles.createText}>Criar empresa</ThemedText></Pressable></Card>}{message && <ThemedText>{message}</ThemedText>}</>}<Pressable onPress={signOut} style={styles.button}><ThemedText style={styles.buttonText}>Sair</ThemedText></Pressable></Screen>;
}
const styles = StyleSheet.create({ input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 13, backgroundColor: '#fff' }, create: { backgroundColor: '#208AEF', borderRadius: 12, alignItems: 'center', padding: 14 }, createText: { color: '#fff', fontWeight: '700' }, button: { backgroundColor: '#b91c1c', borderRadius: 12, alignItems: 'center', padding: 14 }, buttonText: { color: '#fff', fontWeight: '700' } });
