import { useLocalSearchParams, router } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet } from 'react-native';
import { useAuth } from '@/auth/AuthContext';
import { apiRequest } from '@/lib/api';
import { Card, LoadingOrError, Screen } from '@/components/screen';
import { ThemedText } from '@/components/themed-text';

type Member = Record<string, unknown>;
export default function CompanyMemberScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { token } = useAuth(); const [member, setMember] = useState<Member>(); const [companyId, setCompanyId] = useState<string>(); const [me, setMe] = useState<Member>(); const [error, setError] = useState<string>(); const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const profile = await apiRequest<Member>('/users/profile', {}, token ?? undefined); const company = profile.data?.company as Member | undefined; const cid = String(company?.company_id ?? company?.companyId ?? ''); setCompanyId(cid); const response = await apiRequest<{ members?: Member[] }>(`/users/company/${cid}/members`, {}, token ?? undefined); const members = response.data?.members ?? []; setMember(members.find((item) => String(item.user_id ?? item.userId) === id)); setMe(members.find((item) => String(item.user_id ?? item.userId) === String(profile.data?.user_id ?? profile.data?.userId))); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao carregar membro.'); } }, [id, token]);
  useEffect(() => { void load(); }, [load]);
  const isOwner = Boolean(me?.is_owner ?? me?.isOwner); const isAdmin = [1, 2, 4].indexOf(Number(me?.role_id ?? me?.roleId)) !== -1; const canManage = Boolean(member && (isOwner || isAdmin) && String(member.user_id ?? member.userId) !== String(me?.user_id ?? me?.userId) && !(member.is_owner ?? member.isOwner));
  async function action(path: string, method: 'POST' | 'DELETE', body?: unknown) { if (!companyId) return; setBusy(true); try { await apiRequest(path, { method, body: body ? JSON.stringify(body) : undefined }, token ?? undefined); setMessage('Alteração salva.'); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao atualizar membro.'); } finally { setBusy(false); } }
  return <Screen title="Membro da empresa"><Pressable onPress={() => router.back()}><ThemedText type="linkPrimary">Voltar</ThemedText></Pressable><LoadingOrError loading={!member && !error} error={error} />{message && <ThemedText>{message}</ThemedText>}{member && <><Card><ThemedText type="subtitle">{String(member.first_name ?? member.firstName ?? '')} {String(member.last_name ?? member.lastName ?? '')}</ThemedText><ThemedText>{String(member.email ?? '')}</ThemedText><ThemedText>Perfil: {(member.is_owner ?? member.isOwner) ? 'Proprietário' : Number(member.role_id ?? member.roleId) === 2 ? 'Administrador' : 'Membro'}</ThemedText></Card>{canManage ? <><Card><ThemedText type="smallBold">Alterar papel</ThemedText><Pressable disabled={busy} onPress={() => void action('/users/company/members/role', 'POST', { companyId, memberUserId: id, roleId: 2 })}><ThemedText type="linkPrimary">Tornar administrador</ThemedText></Pressable><Pressable disabled={busy} onPress={() => void action('/users/company/members/role', 'POST', { companyId, memberUserId: id, roleId: 3 })}><ThemedText type="linkPrimary">Tornar membro</ThemedText></Pressable></Card><Card><ThemedText type="smallBold">Zona de risco</ThemedText><Pressable disabled={busy} onPress={() => void action('/users/company/members', 'DELETE', { companyId, memberUserId: id })}><ThemedText style={styles.danger}>Remover da empresa</ThemedText></Pressable></Card></> : <ThemedText>Você não tem permissão para administrar este membro.</ThemedText>}</>}</Screen>;
}
const styles = StyleSheet.create({ danger: { color: '#b91c1c', fontWeight: '700' } });
