import { useLocalSearchParams, router } from 'expo-router';
import { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet, TextInput, View } from 'react-native';
import { useAuth } from '@/auth/AuthContext';
import { apiRequest } from '@/lib/api';
import { Card, LoadingOrError, Screen } from '@/components/screen';
import { ThemedText } from '@/components/themed-text';

type User = Record<string, unknown>;
type Tab = 'overview' | 'usage' | 'jobs' | 'documents' | 'limits' | 'logs' | 'settings';
const value = (data: User | undefined, ...keys: string[]) => keys.map((key) => data?.[key]).find((item) => item !== undefined);

export default function AdminUserDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const { token } = useAuth();
  const [user, setUser] = useState<User>(); const [jobs, setJobs] = useState<User[]>([]); const [tab, setTab] = useState<Tab>('overview'); const [error, setError] = useState<string>(); const [message, setMessage] = useState<string>();
  const [blocked, setBlocked] = useState(false); const [flagged, setFlagged] = useState(false); const [limit, setLimit] = useState(''); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { if (!id) return; try { const [u, j] = await Promise.all([apiRequest<User>(`/admin/users/${id}`, {}, token ?? undefined), apiRequest<User>(`/admin/users/${id}/processing-jobs?limit=20&offset=0`, {}, token ?? undefined)]); setUser(u.data); const data = j.data as User; setJobs((data.items ?? data.jobs ?? []) as User[]); const overrides = (u.data?.processing_overrides ?? u.data?.processingOverrides ?? u.data) as User; setBlocked(Boolean(value(overrides, 'blocked_processing', 'blockedProcessing'))); setFlagged(Boolean(value(overrides, 'flagged_processing', 'flaggedProcessing'))); const pageLimit = value(overrides, 'pages_limit_override', 'pagesLimitOverride'); setLimit(pageLimit == null ? '' : String(pageLimit)); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao carregar usuário.'); } }, [id, token]);
  useEffect(() => { void load(); }, [load]);
  async function save() { if (!id) return; setSaving(true); try { await apiRequest(`/admin/users/${id}/processing-overrides`, { method: 'PUT', body: JSON.stringify({ blockedProcessing: blocked, flaggedProcessing: flagged, pagesLimitOverride: limit === '' ? null : Number(limit), processingModelOverride: null }) }, token ?? undefined); setMessage('Configurações salvas.'); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : 'Falha ao salvar configurações.'); } finally { setSaving(false); } }
  const tabs: Tab[] = ['overview', 'usage', 'jobs', 'documents', 'limits', 'logs', 'settings'];
  return <Screen title="Detalhe do usuário"><Pressable onPress={() => router.back()}><ThemedText type="linkPrimary">Voltar</ThemedText></Pressable><View style={styles.tabs}>{tabs.map((item) => <Pressable key={item} onPress={() => setTab(item)} style={[styles.tab, tab === item && styles.activeTab]}><ThemedText>{item === 'overview' ? 'Resumo' : item === 'usage' ? 'Uso' : item === 'jobs' ? 'Jobs' : item === 'documents' ? 'Documentos' : item === 'limits' ? 'Limites' : item === 'logs' ? 'Logs' : 'Configurações'}</ThemedText></Pressable>)}</View><LoadingOrError loading={!user && !error} error={error} />{message && <ThemedText>{message}</ThemedText>}{user && <>
    {(tab === 'overview' || tab === 'usage' || tab === 'documents' || tab === 'limits' || tab === 'logs') && <Card><ThemedText type="smallBold">{tab === 'overview' ? 'Informações básicas' : tab === 'usage' ? 'Uso do usuário' : tab === 'documents' ? 'Documentos processados' : tab === 'limits' ? 'Limites' : 'Logs e atividade'}</ThemedText><ThemedText>{tab === 'overview' ? `${String(user.email ?? '')} · ${String(user.first_name ?? user.firstName ?? '')} ${String(user.last_name ?? user.lastName ?? '')}` : tab === 'usage' ? `Páginas: ${String((user.usage as User | undefined)?.usage_pages ?? (user.usage as User | undefined)?.usagePages ?? 'N/D')} · Jobs: ${String((user.usage as User | undefined)?.processing_job_count ?? (user.usage as User | undefined)?.processingJobCount ?? jobs.length)}` : tab === 'documents' ? `Jobs associados: ${jobs.length}` : tab === 'limits' ? `Limite de páginas: ${limit || 'padrão'}` : 'Eventos administrativos disponíveis no detalhe da conta.'}</ThemedText></Card>}
    {(tab === 'settings' || tab === 'overview') && <Card><ThemedText type="subtitle">Configurações de processamento</ThemedText><Pressable onPress={() => setBlocked((current) => !current)}><ThemedText>{blocked ? '☑' : '☐'} Bloquear processamento</ThemedText></Pressable><Pressable onPress={() => setFlagged((current) => !current)}><ThemedText>{flagged ? '☑' : '☐'} Marcar processamento</ThemedText></Pressable><TextInput value={limit} onChangeText={setLimit} placeholder="Limite de páginas (vazio = padrão)" keyboardType="numeric" style={styles.input} /><Pressable disabled={saving} onPress={() => void save()} style={styles.button}><ThemedText style={styles.white}>{saving ? 'Salvando...' : 'Salvar configurações'}</ThemedText></Pressable></Card>}
    {(tab === 'jobs' || tab === 'overview') && <><ThemedText type="subtitle">Jobs recentes</ThemedText>{jobs.length === 0 && <ThemedText>Nenhum job encontrado.</ThemedText>}{jobs.map((job, i) => <Card key={String(job.process_job_id ?? job.processJobId ?? i)}><ThemedText type="smallBold">{String(job.status ?? '')}</ThemedText><ThemedText>{String(job.file_name ?? job.fileName ?? '')}</ThemedText><ThemedText>{String(job.started_at ?? job.startedAt ?? '')}</ThemedText></Card>)}</>}
  </>}</Screen>;
}
const styles = StyleSheet.create({ tabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 }, tab: { padding: 8, borderRadius: 8, backgroundColor: '#e5e7eb' }, activeTab: { backgroundColor: '#bfe8df' }, input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, padding: 12, backgroundColor: '#fff', marginTop: 8 }, button: { padding: 13, borderRadius: 10, backgroundColor: '#208AEF', alignItems: 'center', marginTop: 10 }, white: { color: '#fff', fontWeight: '700' } });
